In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import json

# 讀森林大火資料

In [14]:
df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/forest-fires/forestfires.csv')

In [15]:
df.head()

   X  Y month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  area
0  7  5   mar  fri  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0   0.0
1  7  4   oct  tue  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0   0.0
2  7  4   oct  sat  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0   0.0
3  8  6   mar  fri  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2   0.0
4  8  6   mar  sun  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0   0.0

# 刪除不必要欄位

In [16]:
df=df.drop("area",axis=1)

In [17]:
df.head()

   X  Y month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain
0  7  5   mar  fri  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0
1  7  4   oct  tue  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0
2  7  4   oct  sat  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0
3  8  6   mar  fri  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2
4  8  6   mar  sun  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0

In [18]:
df=df.drop("rain",axis=1)

In [19]:
df.head()

   X  Y month  day  FFMC   DMC     DC  ISI  temp  RH  wind
0  7  5   mar  fri  86.2  26.2   94.3  5.1   8.2  51   6.7
1  7  4   oct  tue  90.6  35.4  669.1  6.7  18.0  33   0.9
2  7  4   oct  sat  90.6  43.7  686.9  6.7  14.6  33   1.3
3  8  6   mar  fri  91.7  33.3   77.5  9.0   8.3  97   4.0
4  8  6   mar  sun  89.3  51.3  102.2  9.6  11.4  99   1.8

# 依照日期和 FFMC 排名

In [26]:
df_sorted=df.sort_values(by=["month","day","FFMC"],ascending=False)

In [27]:
df_sorted

     X  Y month  day  FFMC    DMC     DC   ISI  temp  RH  wind
45   5  6   sep  wed  94.3   85.1  692.3  15.9  25.9  24   4.0
14   6  5   sep  wed  92.9  133.3  699.6   9.2  26.4  21   4.5
170  5  4   sep  wed  92.9  133.3  699.6   9.2  21.9  35   1.8
193  4  5   sep  wed  92.9  133.3  699.6   9.2  24.3  25   4.0
218  4  5   sep  wed  92.9  133.3  699.6   9.2  19.4  19   1.3
230  4  4   sep  wed  92.9  133.3  699.6   9.2  26.4  21   4.5
313  6  5   sep  wed  92.6  115.4  777.1   8.8  24.3  27   4.9
314  4  4   sep  wed  92.6  115.4  777.1   8.8  19.7  41   1.8
315  3  4   sep  wed  91.2  134.7  817.5   7.2  18.5  30   2.7
44   4  4   sep  wed  90.1   82.9  735.7   6.2  12.9  74   4.9
178  2  5   sep  wed  90.1   82.9  735.7   6.2  18.3  45   2.2
224  7  4   sep  wed  90.1   82.9  735.7   6.2  15.4  57   4.5
448  7  4   sep  wed  89.7  284.9  844.0  10.1  10.5  77   4.0
404  2  4   sep  wed  87.9   84.8  725.1   3.7  21.8  34   2.2
363  4  3   sep  tue  91.9  111.7  770.3   6.5  15.9  53   2.2
364  6  5   sep  tue  91.9  111.7  770.3   6.5  21.1  35   2.7
365  6  5   sep  tue  91.9  111.7  770.3   6.5  19.6  45   3.1
366  4  5   sep  tue  91.1  132.3  812.1  12.5  15.9  38   5.4
367  4  5   sep  tue  91.1  132.3  812.1  12.5  16.4  27   3.6
8    8  6   sep  tue  91.0  129.5  692.6   7.0  13.1  63   5.4
20   6  4   sep  tue  91.0  129.5  692.6   7.0  18.3  40   2.7
139  1  4   sep  tue  91.0  129.5  692.6   7.0  21.7  38   2.2
185  2  5   sep  tue  91.0  129.5  692.6   7.0  17.6  46   3.1
198  3  4   sep  tue  91.0  129.5  692.6   7.0  13.9  59   6.3
200  1  5   sep  tue  91.0  129.5  692.6   7.0  21.6  33   2.2
207  7  5   sep  tue  91.0  129.5  692.6   7.0  20.7  37   2.2
232  6  4   sep  tue  91.0  129.5  692.6   7.0  18.7  43   2.7
237  1  2   sep  tue  91.0  129.5  692.6   7.0  18.8  40   2.2
35   6  3   sep  tue  90.3   80.7  730.2   6.3  18.2  62   4.5
56   4  3   sep  tue  90.3   80.7  730.2   6.3  17.8  63   4.9
..  .. ..   ...  ...   ...    ...    ...   ...   ...  ..   ...
492  1  3   aug  fri  95.9  158.0  633.6  11.3  32.4  27   2.2
493  1  3   aug  fri  95.9  158.0  633.6  11.3  27.5  29   4.5
388  6  4   aug  fri  94.8  227.0  706.7  12.0  23.3  34   3.1
389  7  4   aug  fri  94.8  227.0  706.7  12.0  23.3  34   3.1
402  9  9   aug  fri  94.8  227.0  706.7  12.0  25.0  36   4.0
264  4  4   aug  fri  94.3  167.6  684.4  13.0  21.8  53   3.1
184  8  6   aug  fri  93.9  135.7  586.7  15.1  20.8  34   4.9
195  2  5   aug  fri  93.9  135.7  586.7  15.1  23.5  36   5.4
261  3  4   aug  fri  91.6  112.4  573.0   8.9  11.2  84   7.6
262  2  4   aug  fri  91.6  112.4  573.0   8.9  21.4  42   3.1
263  6  3   aug  fri  91.1  141.1  629.1   7.1  19.3  39   3.6
506  1  2   aug  fri  91.0  166.9  752.6   7.1  18.5  73   8.5
507  2  4   aug  fri  91.0  166.9  752.6   7.1  25.9  41   3.6
508  1  2   aug  fri  91.0  166.9  752.6   7.1  25.9  41   3.6
509  5  4   aug  fri  91.0  166.9  752.6   7.1  21.1  71   7.6
510  6  5   aug  fri  91.0  166.9  752.6   7.1  18.2  62   5.4
434  1  4   aug  fri  90.6  269.8  811.2   5.5  22.2  45   3.6
451  1  4   aug  fri  90.5  196.8  649.9  16.3  11.8  88   4.9
78   1  2   aug  fri  90.1  108.0  529.8  12.5  14.7  66   2.7
142  8  6   aug  fri  90.1  108.0  529.8  12.5  21.2  51   8.9
12   6  5   aug  fri  63.5   70.8  665.3   0.8  17.0  72   6.7
240  6  3   apr  wed  88.0   17.2   43.5   3.8  15.2  51   2.7
176  6  5   apr  thu  81.5    9.1   55.2   2.7   5.8  54   5.8
196  6  5   apr  thu  81.5    9.1   55.2   2.7   5.8  54   5.8
469  6  3   apr  sun  91.0   14.6   25.6  12.3  13.7  33   9.4
470  5  4   apr  sun  91.0   14.6   25.6  12.3  17.6  27   5.8
239  7  5   apr  sun  81.9    3.0    7.9   3.5  13.4  75   1.8
19   6  4   apr  sat  86.3   27.4   97.1   5.1   9.3  44   4.5
442  6  5   apr  mon  87.9   24.9   41.6   3.7  10.9  64   3.1
241  4  4   apr  fri  83.0   23.3   85.3   2.3  16.7  20   3.1

[517 rows x 11 columns]

# 依月分統計

In [37]:
df_area=df.groupby('month').sum()

In [38]:
df_area

         X    Y     FFMC      DMC        DC     ISI    temp    RH   wind
month
apr     52   38    772.1    143.2     437.0    48.4   108.4   422   42.0
aug    825  788  16990.0  28286.8  117958.3  2037.3  3980.2  8370  751.9
dec     41   45    764.7    235.1    3161.2    31.2    40.7   346   68.8
feb    103   88   1658.1    189.5    1093.4    67.0   192.7  1114   75.1
jan      6    9    100.8      4.8     180.7     2.9    10.5   178    4.0
jul    167  147   2922.5   3532.4   14419.3   300.6   707.5  1444  119.5
jun    107   82   1520.3   1587.5    5061.0   200.2   348.4   767   70.3
mar    255  242   4830.0   1865.3    4100.9   383.8   706.5  2160  268.3
may     10    8    174.7     53.4     187.5     9.2    29.3   134    8.9
nov      6    3     79.5      3.0     106.7     1.1    11.8    31    4.5
oct     88   65   1356.8    621.3   10225.1   107.2   256.4   562   51.9
sep    754  708  15693.8  20798.7  126353.9  1475.3  3373.3  7369  611.9